routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',function(){
    return view('dashboard.index');
})->middleware('auth');
Route::resource('order','OrderController')->middleware('auth');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::POST('/totalprice', 'ProductController@gettotal')->name('gettotalprice');
Route::get('export', 'OrderController@export')->name('export');

resources/views/dashboard/add-order.blade.php
@extends('layouts.layout')
@section('css')
    <link href="{{asset('css/select/select2.min.css')}}" rel="stylesheet" />
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add order</h4>
                        <form method="post" action="{{route('order.store')}}">
                            @csrf
                            <div class="form-group">
                                <label for="name" class="col-sm-3 col-form-label">Customer Name</label>
                                <div class="col-sm-5">
                                    <select id="name" class="js-example-basic-single form-control" name="name" data-placeholder="Select Customer Name" >
                                        <option></option>
                                        @foreach($customers as $customer)
                                        <option value="{{$customer->id}}">{{$customer->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                @error('name')
                                <div class="text-danger">
                                    <small><strong>{{ $message }}</strong></small>
                                </div>
                                @enderror
                            </div>
                            <div class="form-group" id="parent">
                                <label for="products" class="col-sm-3 col-form-label">Products</label>
                                <div class="form-group " style="display: flex">
                                <div class="col-sm-2">
                                    <select id="products" class="js-example-basic-single form-control" data-placeholder="Select Product" name="prod[]">
                                       <option></option>
                                        @foreach($products as $product)
                                            <option value="{{$product->id}}">{{$product->product_name}}</option>
                                        @endforeach
                                    </select>
                                    @error('prod[]')
                                    <div class="text-danger">
                                        <small><strong>{{ $message }}</strong></small>
                                    </div>
                                    @enderror
                                </div>
                                <div class="col-sm-2">
                                    <input class="form-control" type="number" name="quan[]" placeholder="Quantity" required>
                                </div>
                                <div class="col-sm-2">
                                    <button type="button" id="plus" onclick="addneworder()" class="btn btn-success">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                                </div>
                            </div>
                            <button type="button" class="btn btn-success" onclick="next()">Continue</button>
                            <div class="form-group hide" >
                                <label for="total" class="col-sm-3 col-form-label">Total</label>
                                <div class="col-sm-5">
                                    <input id="total" class="form-control" type="text" name="totalprice" readonly required>
                                </div>
                            </div>
                            <button type="submit"  class="btn btn-success hide">Add Order</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{asset('js/select/select2.min.js')}}"></script>
<script>
    $(document).ready(function(){
        $('.js-example-basic-single').select2();
        $('.hide').hide();
    });
    function addneworder()
    {
        $('#parent').append('<div class="form-group " style="display: flex">\n' +
            '                                <div class="col-sm-2">\n' +
            '                                    <select class="js-example-basic-single form-control" data-placeholder="Select Product"  name="prod[]"><option></option>\n' +
            '                                        @foreach($products as $product)\n' +
            '                                            <option value="{{$product->id}}">{{$product->product_name}}</option>\n' +
            '                                        @endforeach\n' +
            '                                    </select>\n' +
            '                                    @error('prod[]')\n' +
            '                                    <div class="<div class="text-danger">\n' +
            '                                        <strong>{{ $message }}</strong>\n' +
            '                                    </div>\n' +
            '                                    @enderror\n' +
            '                                </div>\n' +
            '                                <div class="col-sm-2">\n' +
            '                                    <input id="pool_name" class="form-control" type="number" name="quan[]" placeholder="Quantity" required>\n' +
            '                                </div>\n' +
            '                                <div class="col-sm-2">\n' +
            '                                    <button type="button" id="plus" onclick="addneworder()" class="btn btn-success">\n' +
            '                                        <i class="fa fa-plus"></i>\n' +
            '                                    </button>\n' +
            '                                </div>\n' +
            '                                </div>');
        $('.js-example-basic-single').select2();
        $('#parent').before(function(){
            $('#plus').replaceWith("<button type=\"button\" class=\"btn btn-danger\" onclick=\"$(this).parent().parent().remove()\">\n" +
                "                                        <i class=\"fa fa-minus\" id=\"minus\"></i>\n" +
                "                                    </button>");
        });
    }
    function next(){
        var array1=$('select[name="prod[]"]').map(function(){return $(this).val();}).get();
        var array2=$('input[name="quan[]"]').map(function(){return $(this).val();}).get();
        $('.hide').show();
        $.ajax({
            url :'{{route('gettotalprice')}}',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            method:'post',
            data:{products:array1,quantities:array2},
            success : function (data) {
            $('#total').val(data+'$');
            }
        });
    }
</script>
@endsection

resources/views/dashboard/edit-order.blade.php
@extends('layouts.layout')
@section('css')
    <link href="{{asset('css/select/select2.min.css')}}" rel="stylesheet" />
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Edit order</h4>
                        <form method="post" action="{{route('order.update',[$order->id])}}">
                            @csrf
                            @method('PATCH')
                            <div class="form-group">
                                <label for="name" class="col-sm-3 col-form-label">Customer Name</label>
                                <div class="col-sm-5">
                                    <select id="name" class="js-example-basic-single form-control" name="name" data-placeholder="Select Customer Name">
                                        @foreach($customers as $customer)
                                            @if ($order->customer_id==$customer->id)
                                                <option value="{{$customer->id}}" selected>{{$customer->name}}</option>
                                            @else
                                                <option value="{{$customer->id}}">{{$customer->name}}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                    @error('name')
                                    <div class="text-danger">
                                        <small><strong>{{ $message }}</strong></small>
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group" id="parent">
                                <label for="products" class="col-sm-3 col-form-label">Products</label>
                                @foreach($order_details as $details)
                                <div class="form-group " style="display: flex">
                                    <div class="col-sm-2">
                                        <select id="products" class="js-example-basic-single form-control" data-placeholder="Select Product" name="prod[]">
                                            @foreach($products as $product)
                                                @if($details->product_id==$product->id)
                                                <option value="{{$product->id}}" selected>{{$product->product_name}}</option>
                                                @else
                                                <option value="{{$product->id}}">{{$product->product_name}}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                        @error('prod[]')
                                        <div class="text-danger">
                                            <small><strong>{{ $message }}</strong></small>
                                        </div>
                                        @enderror
                                    </div>
                                    <div class="col-sm-2">
                                        <input class="form-control" type="number" name="quan[]" value="{{$details->quantity}}" placeholder="Quantity" required>
                                    </div>
                                    @if($loop->last)
                                    <div class="col-sm-2">
                                        <button type="button" id="plus" onclick="addneworder()" class="btn btn-success">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                    @else
                                        <div class="col-sm-2">
                                        <button type="button" class="btn btn-danger" onclick="$(this).parent().parent().remove()">
                                            <i class="fa fa-minus" id="minus"></i>
                                        </button>
                                        </div>
                                    @endif
                                </div>
                                @endforeach
                            </div>
                            <button type="button" class="btn btn-success" onclick="next()">Continue</button>
                            <div class="form-group hide" >
                                <label for="total" class="col-sm-3 col-form-label">Total</label>
                                <div class="col-sm-5">
                                    <input id="total" class="form-control" type="text" value="{{old('totalprice')}}" name="totalprice" readonly required>
                                </div>
                            </div>
                            <button type="submit"  class="btn btn-success hide">Edit Order</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{asset('js/select/select2.min.js')}}"></script>
    <script>
        $(document).ready(function(){
            $('.js-example-basic-single').select2();
            $('.hide').hide();
        });
        function addneworder()
        {
            $('#parent').append('<div class="form-group " style="display: flex">\n' +
                '                                <div class="col-sm-2">\n' +
                '                                    <select class="js-example-basic-single form-control"  data-placeholder="Select Product"  name="prod[]"><option></option>\n' +
                '                                        @foreach($products as $product)\n' +
                '                                            <option value="{{$product->id}}">{{$product->product_name}}</option>\n' +
                '                                        @endforeach\n' +
                '                                    </select>\n' +
                '                                    @error('prod[]')\n' +
                '                                    <div class="text-danger">\n' +
                '                                        <strong>{{ $message }}</strong>\n' +
                '                                    </span>\n' +
                '                                    @enderror\n' +
                '                                </div>\n' +
                '                                <div class="col-sm-2">\n' +
                '                                    <input id="pool_name" class="form-control" type="number" name="quan[]" placeholder="Quantity" required>\n' +
                '                                </div>\n' +
                '                                <div class="col-sm-2">\n' +
                '                                    <button type="button" id="plus" onclick="addneworder()" class="btn btn-success">\n' +
                '                                        <i class="fa fa-plus"></i>\n' +
                '                                    </button>\n' +
                '                                </div>\n' +
                '                                </div>');
            $('.js-example-basic-single').select2();
            $('#parent').before(function(){
                $('#plus').replaceWith("<button type=\"button\" class=\"btn btn-danger\" onclick=\"$(this).parent().parent().remove()\">\n" +
                    "                                        <i class=\"fa fa-minus\" id=\"minus\"></i>\n" +
                    "                                    </button>");
            });
        }
        function next(){
            var array1=$('select[name="prod[]"]').map(function(){return $(this).val();}).get();
            var array2=$('input[name="quan[]"]').map(function(){return $(this).val();}).get();
            $('.hide').show();
            $.ajax({
                url :'{{route('gettotalprice')}}',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method:'post',
                data:{products:array1,quantities:array2},
                success : function (data) {
                    $('#total').val(data+'$');
                }
            });
        }
    </script>
@endsection

resources/views/dashboard/index.blade.php
@extends('layouts.layout')
@section('css')
    <link rel="stylesheet" href="../../node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css"/>
@endsection
@section('content')
    <div class="content-wrapper">
        <img src="{{URL::to('images/unnamed.png')}}" alt="logo" style="margin-top: 20%;
    margin-left: 40%;">
    </div>
@endsection

resources/views/dashboard/order.blade.php
@extends('layouts.layout')
@section('css')
    <link rel="stylesheet" href="{{asset('node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{asset('../../node_modules/sweetalert2/dist/sweetalert2.min.css')}}">
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="card">
            <div class="card-body">
                <div class="col-sm-12 col-12 text-right my-2">
                    <a href="{{route('order.create')}}" class="btn btn btn-outline-success btn-rounded float-right"><i class="fa fa-plus"></i>Add Order</a>
                    <a class="mr-1 btn btn btn-outline-warning btn-rounded float-right " href="{{ route('export') }}">Export Order's Data</a>
                </div>
                <h4 class="card-title">Orders</h4>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table id="order-listing" class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Customer Name</th>
                                    <th>date</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($orders as $order)
                                    <tr>
                                        <td>{{$loop->index+1}}</td>
                                        <td>{{$order->customer->name}}</td>
                                        <td>{{$order->created_at}}</td>
                                        <td>
                                            <a class="btn btn-primary" href="{{route('order.edit',[$order->id])}}" ><i class="fa fa-pencil-square-o"></i></a>
                                            <button class="btn btn-danger" onclick="deleteItem({{$order->id}})"><i class="fa fa-trash"></i></button>
                                        </td>
                                    </tr>
                                @endforeach
                                @if (session('message'))
                                    <div class="alert alert-success">
                                        {{ session('message') }}
                                    </div>
                                @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form method="post" action="" id="deleteForm">
        @csrf
        @method('DELETE')
    </form>
@endsection
@section('scripts')
    <script src="{{asset('node_modules/datatables.net/js/jquery.dataTables.js')}}"></script>
    <script src="{{asset('node_modules/datatables.net-bs4/js/dataTables.bootstrap4.js')}}"></script>
    <script src="node_modules/sweetalert2/dist/sweetalert2.min.js"></script>
    <script src="node_modules/jquery.avgrund/jquery.avgrund.min.js"></script>
    <script>
        var message="{{Session::get('success')}}";
        if(message!='')
        {
            swal(
                'Done!',
                message,
                'success'
            ).catch(swal.noop);
        }
    </script>
    <script>
        function deleteItem(id)
        {
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Delete '
            }).then((result) =>  {

                if (result) {

                    $('#deleteForm').attr('action','/order/'+id);
                    $('#deleteForm').submit();
                }
            }).catch(swal.noop);
        }
    </script>
    <script>
        $(document).ready( function () {
            $('.table').DataTable();
        } );
    </script>

@endsection